from .base import * # noqa F403

SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
CORS_ALLOWED_ORIGINS = [env("DJANGO_CORS_ALLOWED_ORIGINS").split(",")] # noqa F405
ALLOWED_HOSTS = [env("DJANGO_ALLOWED_HOSTS").split(",")] # noqa F405
